### ISSUE TITLE
Could not execute bash navi10/22.rocblas.sh succesfully

### ISSUE THREAD

**Issue by DaverSVK** [xuhuisheng/rocm-build#48]
### Environment

| Hardware | description   |
|----------|---------------|
| GPU      | -   RX 5700 XT    |
| CPU      | -   Ryzen 9 5900X         |

| Software | version |
|----------|---------|
| OS       | -   Linux    |
| ROCm     | -   5.4.    |
| Python   | -     3.8.10  |

### What is the expected behavior

- command $ sudo bash navi10/22.rocblas.sh

### What actually happens

```
|====|
|SLOW|
|====|
/home/work/rocm-build/build/rocblas /home/work/rocm-build/build/rocblas
/home/work/rocm-build/patch

succesfull
-- Use hip-clang to build for amdgpu backend
-- OS detected is ubuntu
/usr/bin/python3 -m venv /home/work/rocm-build/build/rocblas/virtualenv --system-site-packages --clear
virtualenv python version: /home/work/rocm-build/build/rocblas/virtualenv/bin/python3
Python 3.8.10
/home/work/rocm-build/build/rocblas/virtualenv/bin/python3 -m pip install /home/work/ROCm/Tensile
Processing /home/work/ROCm/Tensile
Collecting msgpack
  Using cached msgpack-1.0.8-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (390 kB)
Requirement already satisfied: pyyaml in /usr/lib/python3/dist-packages (from Tensile==4.35.0) (5.3.1)
Building wheels for collected packages: Tensile
  Building wheel for Tensile (setup.py): started
  Building wheel for Tensile (setup.py): finished with status 'done'
  Created wheel for Tensile: filename=Tensile-4.35.0-py3-none-any.whl size=4648915 sha256=2485a4a280f6700fcd09f1ee1a87db1d345a1d13c440cd779842b60178e22b81
  Stored in directory: /tmp/pip-ephem-wheel-cache-n2z01yja/wheels/cb/cc/4d/d680bcd421b8de332591005aa3a239083cfcbdab768ddf405b
Successfully built Tensile
Installing collected packages: msgpack, Tensile
Successfully installed Tensile-4.35.0 msgpack-1.0.8
-- using local Tensile from /home/work/ROCm/Tensile, copied to 
-- Adding /home/work/rocm-build/build/rocblas/virtualenv to CMAKE_PREFIX_PATH
-- Using AMDGPU_TARGETS: 
CMake Warning at /home/work/rocm-build/build/rocblas/virtualenv/cmake/TensileConfig.cmake:140 (message):
  Malformed arguments: ARCHITECTURE
Call Stack (most recent call first):
  library/src/CMakeLists.txt:100 (TensileCreateLibraryFiles)


-- Tensile script: /home/work/rocm-build/build/rocblas/virtualenv/lib/python3.8/site-packages/Tensile/bin/TensileCreateLibrary
-- Tensile_CREATE_COMMAND: /home/work/rocm-build/build/rocblas/virtualenv/lib/python3.8/site-packages/Tensile/bin/TensileCreateLibrary;--merge-files;--separate-architectures;--lazy-library-loading;--no-short-file-names;--no-library-print-debug;--code-object-version=V3;--cxx-compiler=hipcc;--library-format=msgpack;/home/work/ROCm/rocBLAS/library/src/blas3/Tensile/Logic/asm_full;/home/work/rocm-build/build/rocblas/Tensile;HIP
-- Tensile_MANIFEST_FILE_PATH: /home/work/rocm-build/build/rocblas/Tensile/library/TensileManifest.txt
'/home/work/rocm-build/build/rocblas/virtualenv/lib/python3.8/site-packages/Tensile/bin/TensileCreateLibrary' '--merge-files' '--separate-architectures' '--lazy-library-loading' '--no-short-file-names' '--no-library-print-debug' '--code-object-version=V3' '--cxx-compiler=hipcc' '--library-format=msgpack' '/home/work/ROCm/rocBLAS/library/src/blas3/Tensile/Logic/asm_full' '/home/work/rocm-build/build/rocblas/Tensile' 'HIP' '--generate-manifest-and-exit'

################################################################################
# Tensile Create Library
# Detected local GPU with ISA: gfx1010
# Detected local GPU with ISA: gfx1010
# Detected local GPU with ISA: gfx1010
# Detected local GPU with ISA: gfx1010
# Detected local GPU with ISA: gfx1010
                 cap gfx000 gfx1010 
     HasMFMA_bf16_1k      0       0 
          HasAddLshl      0       1 
        HasAtomicAdd      0       0 
     HasCodeObjectV3      0       1 
  HasDirectToLdsDest      0       0 
HasDirectToLdsNoDest      0       1 
       HasExplicitCO      0       1 
       HasExplicitNC      0       1 
           HasLshlOr      0       1 
             HasMFMA      0       0 
           HasSMulHi      0       1 
          MaxLgkmcnt      1       1 
            MaxVmcnt      0       1 
        SupportedISA      0       1 
     SupportedSource      1       1 
      v_dot2_f32_f16      0       0 
     v_dot2c_f32_f16      0       0 
           v_fma_f16      0       1 
          v_fmac_f16      0       0 
           v_mac_f16      0       0 
        v_pk_fma_f16      0       1 
       v_pk_fmac_f16      0       0 
           v_fma_f32      0       1 
       v_fma_mix_f32      0       1 
          v_fmac_f32      0       1 
           v_mac_f32      0       1 
       v_mad_mix_f32      0       0 
         HasMFMA_f64      0       0 
           v_fma_f64      0       1 
   VOP3v_dot4_i32_i8      0       0 
       v_dot4_i32_i8      0       0 
      v_dot4c_i32_i8      0       0 
  ArchAccUnifiedRegs      0       0 
      CMPXWritesSGPR      1       0 
            HasAccCD      0       0 
          HasEccHalf      0       0 
           HasWave32      0       1 
       SeparateVscnt      0       1 
    Waitcnt0Disabled      0       0 
# Found  hipcc version 6.1.40093-bd86f1708
# CodeObjectVersion from TensileCreateLibrary: V3
# CxxCompiler       from TensileCreateLibrary: hipcc
# Architecture      from TensileCreateLibrary: all
# LibraryFormat     from TensileCreateLibrary: msgpack
# LibraryLogicFiles:
#   /home/work/ROCm/rocBLAS/library/src/blas3/Tensile/Logic/asm_full/hip/hip_Cijk_Alik_Bjlk_SB.yaml
#   /home/work/ROCm/rocBLAS/library/src/blas3/Tensile/Logic/asm_full/hip/hip_Cijk_Ailk_Bljk_HB.yaml
#   /home/work/ROCm/rocBLAS/library/src/blas3/Tensile/Logic/asm_full/hip/hip_Cijk_Ailk_BjlkC_ZB.yaml
#   /home/work/ROCm/rocBLAS/library/src/blas3/Tensile/Logic/asm_full/hip/hip_Cijk_Alik_Bljk_BSS_BH_GB.yaml
#   /home/work/ROCm/rocBLAS/library/src/blas3/Tensile/Logic/asm_full/hip/hip_Cijk_Alik_Bjlk_BSS_BH_GB.yaml
#   /home/work/ROCm/rocBLAS/library/src/blas3/Tensile/Logic/asm_full/hip/hip_Cijk_Ailk_Bljk_CB.yaml
#   /home/work/ROCm/rocBLAS/library/src/blas3/Tensile/Logic/asm_full/hip/hip_Cijk_Ailk_Bljk_DB_GB.yaml
#   /home/work/ROCm/rocBLAS/library/src/blas3/Tensile/Logic/asm_full/hip/hip_Cijk_Alik_Bjlk_CB.yaml
#   /home/work/ROCm/rocBLAS/library/src/blas3/Tensile/Logic/asm_full/hip/hip_Cijk_AlikC_Bjlk_CB.yaml
#   /home/work/ROCm/rocBLAS/library/src/blas3/Tensile/Logic/asm_full/hip/hip_Cijk_Alik_Bljk_I8II_BH.yaml
#   /home/work/ROCm/rocBLAS/library/src/blas3/Tensile/Logic/asm_full/hip/hip_Cijk_Ailk_Bjlk_HHS_BH.yaml
#   /home/work/ROCm/rocBLAS/library/src/blas3/Tensile/Logic/asm_full/hip/hip_Cijk_Ailk_Bjlk_4xi8II_BH_GB.yaml
#   /home/work/ROCm/rocBLAS/library/src/blas3/Tensile/Logic/asm_full/hip/hip_Cijk_Alik_Bljk_ZB.yaml
#   /home/work/ROCm/rocBLAS/library/src/blas3/Tensile/Logic/asm_full/hip/hip_Cijk_Alik_BjlkC_CB_GB.yaml
#   /home/work/ROCm/rocBLAS/library/src/blas3/Tensile/Logic/asm_full/hip/hip_Cijk_Alik_Bljk_DB.yaml
#   /home/work/ROCm/rocBLAS/library/src/blas3/Tensile/Logic/asm_full/hip/hip_Cijk_Alik_Bjlk_BBS_BH.yaml
#   /home/work/ROCm/rocBLAS/library/src/blas3/Tensile/Logic/asm_full/hip/hip_Cijk_Ailk_Bljk_BSS_BH.yaml
#   /home/work/ROCm/rocBLAS/library/src/blas3/Tensile/Logic/asm_full/hip/hip_Cijk_AlikC_Bljk_CB_GB.yaml
#   /home/work/ROCm/rocBLAS/library/src/blas3/Tensile/Logic/asm_full/hip/hip_Cijk_Alik_Bljk_SB.yaml
#   /home/work/ROCm/rocBLAS/library/src/blas3/Tensile/Logic/asm_full/hip/hip_Cijk_Alik_Bljk_HHS_BH.yaml
#   /home/work/ROCm/rocBLAS/library/src/blas3/Tensile/Logic/asm_full/hip/hip_Cijk_Alik_Bljk_CB.yaml
#   /home/work/ROCm/rocBLAS/library/src/blas3/Tensile/Logic/asm_full/hip/hip_Cijk_Alik_Bjlk_HHS_BH_GB.yaml
#   /home/work/ROCm/rocBLAS/library/src/blas3/Tensile/Logic/asm_full/hip/hip_Cijk_Alik_Bljk_HHS_BH_GB.yaml
....Many more files
#   /home/work/ROCm/rocBLAS/library/src/blas3/Tensile/Logic/asm_full/aldebaran/equality/aldebaran_Cijk_Ailk_Bljk_HHS_BH.yaml
#   /home/work/ROCm/rocBLAS/library/src/blas3/Tensile/Logic/asm_full/aldebaran/equality/aldebaran_Cijk_Ailk_Bljk_SB.yaml
#   /home/work/ROCm/rocBLAS/library/src/blas3/Tensile/Logic/asm_full/aldebaran/fp16altimpl/aldebaran_Cijk_Alik_Bjlk_HHS_BHR.yaml
#   /home/work/ROCm/rocBLAS/library/src/blas3/Tensile/Logic/asm_full/aldebaran/fp16altimpl/aldebaran_Cijk_Alik_Bljk_HHS_BHR.yaml
#   /home/work/ROCm/rocBLAS/library/src/blas3/Tensile/Logic/asm_full/aldebaran/fp16altimpl/aldebaran_Cijk_Ailk_Bljk_HHS_BHR.yaml
#   /home/work/ROCm/rocBLAS/library/src/blas3/Tensile/Logic/asm_full/aldebaran/fp16altimpl/aldebaran_Cijk_Ailk_Bjlk_HHS_BHR.yaml
Reading logic files: Launching 24 threads...
Traceback (most recent call last):
  File "/home/work/rocm-build/build/rocblas/virtualenv/lib/python3.8/site-packages/Tensile/Parallel.py", line 57, in apply_print_exception
    return func(item)
  File "/home/work/rocm-build/build/rocblas/virtualenv/lib/python3.8/site-packages/Tensile/LibraryIO.py", line 170, in parseLibraryLogicFile
    return parseLibraryLogicData(readYAML(filename), filename)
  File "/home/work/rocm-build/build/rocblas/virtualenv/lib/python3.8/site-packages/Tensile/LibraryIO.py", line 202, in parseLibraryLogicData
    solutionObject = Solution(solutionState)
  File "/home/work/rocm-build/build/rocblas/virtualenv/lib/python3.8/site-packages/Tensile/SolutionStructs.py", line 1748, in __init__
    Solution.assignDerivedParameters(self._state)
  File "/home/work/rocm-build/build/rocblas/virtualenv/lib/python3.8/site-packages/Tensile/SolutionStructs.py", line 3700, in assignDerivedParameters
    if globalParameters["ArchCaps"][isa]["HasAccCD"] and \
KeyError: (11, 0, 1)
Traceback (most recent call last):
  File "/home/work/rocm-build/build/rocblas/virtualenv/lib/python3.8/site-packages/Tensile/Parallel.py", line 57, in apply_print_exception
    return func(item)
  File "/home/work/rocm-build/build/rocblas/virtualenv/lib/python3.8/site-packages/Tensile/LibraryIO.py", line 170, in parseLibraryLogicFile
    return parseLibraryLogicData(readYAML(filename), filename)
  File "/home/work/rocm-build/build/rocblas/virtualenv/lib/python3.8/site-packages/Tensile/LibraryIO.py", line 202, in parseLibraryLogicData
    solutionObject = Solution(solutionState)
  File "/home/work/rocm-build/build/rocblas/virtualenv/lib/python3.8/site-packages/Tensile/SolutionStructs.py", line 1748, in __init__
    Solution.assignDerivedParameters(self._state)
  File "/home/work/rocm-build/build/rocblas/virtualenv/lib/python3.8/site-packages/Tensile/SolutionStructs.py", line 3700, in assignDerivedParameters
    if globalParameters["ArchCaps"][isa]["HasAccCD"] and \
KeyError: (9, 0, 6)
.
.More similar messages
.
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/work/rocm-build/build/rocblas/virtualenv/lib/python3.8/site-packages/Tensile/Parallel.py", line 57, in apply_print_exception
    return func(item)
  File "/home/work/rocm-build/build/rocblas/virtualenv/lib/python3.8/site-packages/Tensile/LibraryIO.py", line 170, in parseLibraryLogicFile
    return parseLibraryLogicData(readYAML(filename), filename)
  File "/home/work/rocm-build/build/rocblas/virtualenv/lib/python3.8/site-packages/Tensile/LibraryIO.py", line 202, in parseLibraryLogicData
    solutionObject = Solution(solutionState)
  File "/home/work/rocm-build/build/rocblas/virtualenv/lib/python3.8/site-packages/Tensile/SolutionStructs.py", line 1748, in __init__
    Solution.assignDerivedParameters(self._state)
  File "/home/work/rocm-build/build/rocblas/virtualenv/lib/python3.8/site-packages/Tensile/SolutionStructs.py", line 3700, in assignDerivedParameters
    if globalParameters["ArchCaps"][isa]["HasAccCD"] and \
KeyError: (11, 0, 1)
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/work/rocm-build/build/rocblas/virtualenv/lib/python3.8/site-packages/Tensile/bin/TensileCreateLibrary", line 43, in <module>
    TensileCreateLibrary()
  File "/home/work/rocm-build/build/rocblas/virtualenv/lib/python3.8/site-packages/Tensile/TensileCreateLibrary.py", line 1275, in TensileCreateLibrary
    solutions, masterLibraries, fullMasterLibrary = generateLogicDataAndSolutions(logicFiles, args)
  File "/home/work/rocm-build/build/rocblas/virtualenv/lib/python3.8/site-packages/Tensile/TensileCreateLibrary.py", line 1018, in generateLogicDataAndSolutions
    libraries = Common.ParallelMap(LibraryIO.parseLibraryLogicFile, logicFiles, "Reading logic files")
  File "/home/work/rocm-build/build/rocblas/virtualenv/lib/python3.8/site-packages/Tensile/Parallel.py", line 134, in ParallelMap
    rv = mapFunc(function, objects)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
KeyError: (11, 0, 1)
CMake Error at /home/work/rocm-build/build/rocblas/virtualenv/cmake/TensileConfig.cmake:265 (message):
  Error creating Tensile library: 1
Call Stack (most recent call first):
  library/src/CMakeLists.txt:100 (TensileCreateLibraryFiles)


-- Configuring incomplete, errors occurred!

```

-

### How to reproduce
```

-Operating system ubuntu 20.04.5 
Step by step guide:
https://github.com/xuhuisheng/rocm-build/tree/master/navi10
rocBLAST 
in dir /home/work
`$ git clone https://github.com/RadeonOpenCompute/ROCm.git -b roc-5.4.x`
cd ROCm
I made sure everithing is as suppose to be
```
 $ git status
 $ git pull
```
Installed rocBLAS and Tensile
`$ git clone https://github.com/ROCmSoftwarePlatform/rocBLAS.git -b release/rocm-rel-5.4`
`$ git clone https://github.com/ROCmSoftwarePlatform/Tensile.git -b release/rocm-rel-5.4`
- 
changed pathts in 22.rocblas.sh bcs of error
++ROCM_GIT_DIR="/home/work/ROCm"
++ROCM_BUILD_DIR="/home/work/rocm-build/build"
++ROCM_PATCH_DIR="/home/work/rocm-build/patch"

Pached manualy bcs of conflict
-> Tensile/Common.py
++globalParameters["SupportedISA"] = [(10,1,0)]
-----------------------------------------------------------------------------------------------------------------------------------------------------------------
Instaled Cmake via this 
https://askubuntu.com/questions/829310/how-to-upgrade-cmake-in-ubuntu
bcs normal sudo apt install cmake instaled old version
`$ sudo apt-get install ninja-build`
`$ sudo apt install python3.8-venv`
` $ sudo apt-get install libmsgpack-dev`
`$ sudo nano navi10/22.rocblas.sh `
|====|
|SLOW|
|====|
/home/work/rocm-build/build/rocblas /home/work/rocm-build/build/rocblas
/home/work/rocm-build/patch

-- Use hip-clang to build for amdgpu backend
-- OS detected is ubuntu
/usr/bin/python3 -m venv /home/work/rocm-build/build/rocblas/virtualenv --system-site-packages --clear
virtualenv python version: /home/work/rocm-build/build/rocblas/virtualenv/bin/python3
Python 3.8.10
/home/work/rocm-build/build/rocblas/virtualenv/bin/python3 -m pip install /home/work/ROCm/Tensile
Processing /home/work/ROCm/Tensile
Collecting msgpack
  Using cached msgpack-1.0.8-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (390 kB)
Requirement already satisfied: pyyaml in /usr/lib/python3/dist-packages (from Tensile==4.35.0) (5.3.1)
Building wheels for collected packages: Tensile
  Building wheel for Tensile (setup.py): started
  Building wheel for Tensile (setup.py): finished with status 'done'
  Created wheel for Tensile: filename=Tensile-4.35.0-py3-none-any.whl size=4648920 sha256=c1dde53b0de5aa707652ed178e209b170437c96b16813de0cdcd09f6e1a505d2
  Stored in directory: /tmp/pip-ephem-wheel-cache-obb_gado/wheels/cb/cc/4d/d680bcd421b8de332591005aa3a239083cfcbdab768ddf405b
Successfully built Tensile
Installing collected packages: msgpack, Tensile
Successfully installed Tensile-4.35.0 msgpack-1.0.8
-- using local Tensile from /home/work/ROCm/Tensile, copied to 
-- Adding /home/work/rocm-build/build/rocblas/virtualenv to CMAKE_PREFIX_PATH
-- Using AMDGPU_TARGETS: 
CMake Warning at /home/work/rocm-build/build/rocblas/virtualenv/cmake/TensileConfig.cmake:140 (message):
  Malformed arguments: ARCHITECTURE
Call Stack (most recent call first):
  library/src/CMakeLists.txt:100 (TensileCreateLibraryFiles)


-- Tensile script: /home/work/rocm-build/build/rocblas/virtualenv/lib/python3.8/site-packages/Tensile/bin/TensileCreateLibrary
-- Tensile_CREATE_COMMAND: /home/work/rocm-build/build/rocblas/virtualenv/lib/python3.8/site-packages/Tensile/bin/TensileCreateLibrary;--merge-files;--lazy-library-loading;--no-short-file-names;--no-library-print-debug;--code-object-version=V3;--cxx-compiler=hipcc;--library-format=msgpack;/home/work/ROCm/rocBLAS/library/src/blas3/Tensile/Logic/asm_full;/home/work/rocm-build/build/rocblas/Tensile;HIP
-- Tensile_MANIFEST_FILE_PATH: /home/work/rocm-build/build/rocblas/Tensile/library/TensileManifest.txt
'/home/work/rocm-build/build/rocblas/virtualenv/lib/python3.8/site-packages/Tensile/bin/TensileCreateLibrary' '--merge-files' '--lazy-library-loading' '--no-short-file-names' '--no-library-print-debug' '--code-object-version=V3' '--cxx-compiler=hipcc' '--library-format=msgpack' '/home/work/ROCm/rocBLAS/library/src/blas3/Tensile/Logic/asm_full' '/home/work/rocm-build/build/rocblas/Tensile' 'HIP' '--generate-manifest-and-exit'

################################################################################
# Tensile Create Library
# Detected local GPU with ISA: gfx1010
# Detected local GPU with ISA: gfx1010
# Detected local GPU with ISA: gfx1010
# Detected local GPU with ISA: gfx1010
# Detected local GPU with ISA: gfx1010
                 cap gfx000 gfx1010 
     HasMFMA_bf16_1k      0       0 
          HasAddLshl      0       1 
        HasAtomicAdd      0       0 
     HasCodeObjectV3      0       1 
  HasDirectToLdsDest      0       0 
HasDirectToLdsNoDest      0       1 
       HasExplicitCO      0       1 
       HasExplicitNC      0       1 
           HasLshlOr      0       1 
             HasMFMA      0       0 
           HasSMulHi      0       1 
          MaxLgkmcnt      1       1 
            MaxVmcnt      0       1 
        SupportedISA      0       1 
     SupportedSource      1       1 
      v_dot2_f32_f16      0       0 
     v_dot2c_f32_f16      0       0 
           v_fma_f16      0       1 
          v_fmac_f16      0       0 
           v_mac_f16      0       0 
        v_pk_fma_f16      0       1 
       v_pk_fmac_f16      0       0 
           v_fma_f32      0       1 
       v_fma_mix_f32      0       1 
          v_fmac_f32      0       1 
           v_mac_f32      0       1 
       v_mad_mix_f32      0       0 
         HasMFMA_f64      0       0 
           v_fma_f64      0       1 
   VOP3v_dot4_i32_i8      0       0 
       v_dot4_i32_i8      0       0 
      v_dot4c_i32_i8      0       0 
  ArchAccUnifiedRegs      0       0 
      CMPXWritesSGPR      1       0 
            HasAccCD      0       0 
          HasEccHalf      0       0 
           HasWave32      0       1 
       SeparateVscnt      0       1 
    Waitcnt0Disabled      0       0 
# Found  hipcc version 6.1.40093-bd86f1708
# CodeObjectVersion from TensileCreateLibrary: V3
# CxxCompiler       from TensileCreateLibrary: hipcc
# Architecture      from TensileCreateLibrary: all
# LibraryFormat     from TensileCreateLibrary: msgpack
Tensile::FATAL: --lazy-library-loading requires --merge-files and --separate-architectures enabled
CMake Error at /home/work/rocm-build/build/rocblas/virtualenv/cmake/TensileConfig.cmake:265 (message):
  Error creating Tensile library: 255
Call Stack (most recent call first):
  library/src/CMakeLists.txt:100 (TensileCreateLibraryFiles)


-- Configuring incomplete, errors occurred!
-------------------------------------------------------------------------------------------

I tried to tweak the navi10/22.rocblas.sh file 

```
CXX=$ROCM_INSTALL_DIR/bin/hipcc cmake \
    -DCMAKE_TOOLCHAIN_FILE=toolchain-linux.cmake \
    -DAMDGPU_TARGETS=$AMDGPU_TARGETS \
    -DROCM_PATH=$ROCM_INSTALL_DIR \
    -DTensile_LOGIC=asm_full \
    -DTensile_ARCHITECTURE=gfx1010 \
    -DTensile_CODE_OBJECT_VERSION=V3 \
    -DTensile_SEPARATE_ARCHITECTURES=OFF \
    -DTensile_MERGE_ARCHITECTURES=ON \			#Added
    -DTensile_LAZY_LIBRARY_LOADING=OFF \			#Added
    -DCMAKE_BUILD_TYPE=Release \
    -DTensile_TEST_LOCAL_PATH=$ROCM_GIT_DIR/Tensile \
    -DTensile_LIBRARY_FORMAT=msgpack \
    -DRUN_HEADER_TESTING=OFF \
    -DBUILD_FILE_REORG_BACKWARD_COMPATIBILITY=ON \
    -DCMAKE_INSTALL_PREFIX=rocblas-install \
    -DCPACK_SET_DESTDIR=OFF \
    -DCPACK_PACKAGING_INSTALL_PREFIX=$ROCM_INSTALL_DIR \
    -DCPACK_GENERATOR=DEB \
    -G Ninja \
    $ROCM_GIT_DIR/rocBLAS
```
Then Error above that i couldnt resolve for a while
```

**Comment by DaverSVK** [comment]
I resolved it. Just my enviroment variebles were all over the place and i needed to add them directly into navi10/22.rocblas.sh IDK why source env.sh does not worked as expected.
Anyway It ended up here:
```FAILED: Tensile/lib/CMakeFiles/TensileHost.dir/source/hip/HipHardware.cpp.o 
/opt/rocm/bin/hipcc -DTENSILE_DEFAULT_SERIALIZATION -DTENSILE_MSGPACK=1 -DTENSILE_USE_HIP -DUSE_PROF_API=1 -D__HIP_PLATFORM_AMD__=1 -I/home/work/rocm-build/build/rocblas/virtualenv/lib/python3.8/site-packages/Tensile/Source/lib/include -D__HIP_HCC_COMPAT_MODE__=1 -O3 -DNDEBUG -std=c++14 -fPIC -Wno-unused-result -x hip -MD -MT Tensile/lib/CMakeFiles/TensileHost.dir/source/hip/HipHardware.cpp.o -MF Tensile/lib/CMakeFiles/TensileHost.dir/source/hip/HipHardware.cpp.o.d -o Tensile/lib/CMakeFiles/TensileHost.dir/source/hip/HipHardware.cpp.o -c /home/work/rocm-build/build/rocblas/virtualenv/lib/python3.8/site-packages/Tensile/Source/lib/source/hip/HipHardware.cpp
/home/work/rocm-build/build/rocblas/virtualenv/lib/python3.8/site-packages/Tensile/Source/lib/source/hip/HipHardware.cpp:36:58: error: no member named 'gcnArch' in 'hipDeviceProp_tR0600'
   36 |             : AMDGPU(static_cast<AMDGPU::Processor>(prop.gcnArch),
      |                                                     ~~~~ ^
1 error generated when compiling for gfx1010.
```
For the time being i will do my best to get to the end succesfully
